const data = [
  {
    id: 8,
    name: 'Đắc Nhân Tâm',
    price: '150.000đ',
    img: require('./img/DacNhanTam.jpg'),
    catalog: 'Sách bán chạy',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 9,
    name: 'Homo Deus',
    price: '80.000đ',
    img: require('./img/HomoDeus.jpg'),
    catalog: 'Sách bán chạy',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 10,
    name: 'Nhà Giả Kim',
    price: '120.000đ',
    img: require('./img/NhaGiaKim.jpg'),
    catalog: 'Sách bán chạy',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 11,
    name: 'Sapiens',
    price: '100.000đ',
    img: require('./img/Sapiens.jpg'),
    catalog: 'Sách bán chạy',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 12,
    name: 'Trên Đường Băng',
    price: '80.000đ',
    img: require('./img/TrenDuongBang.jpg'),
    catalog: 'Sách bán chạy',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
];
export default data;
