const data = [
  {
    id: 1,
    name: '1Q84',
    price: '100.000đ',
    img: require('./img/1q84.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 2,
    name: 'Colour Book',
    price: '120.000đ',
    img: require('./img/ColourBook.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 3,
    name: 'Đắc Nhân Tâm',
    price: '150.000đ',
    img: require('./img/DacNhanTam.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 4,
    name: 'Homo Deus',
    price: '80.000đ',
    img: require('./img/HomoDeus.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 5,
    name: 'Nhà Giả Kim',
    price: '120.000đ',
    img: require('./img/NhaGiaKim.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 6,
    name: 'Sapiens',
    price: '100.000đ',
    img: require('./img/Sapiens.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
  {
    id: 7,
    name: 'Trên Đường Băng',
    price: '80.000đ',
    img: require('./img/TrenDuongBang.jpg'),
    catalog: 'Sách tổng hợp',
    supplier: 'JSAddicted',
    size: '16 x 24 cm',
    translator: 'JSAddicted',
    typeofcover: 'Bìa mềm',
    pagesnumber: '554',
    publisher: 'Nhà xuất bản JSAddicted',
  },
];
export default data;
